### ISSUE TITLE
Support anvil 1.18

### ISSUE THREAD

**Issue by Karanztez** [Athlaeos/EnchantsSquared#1]
Need support anvil

**Comment by Athlaeos** [comment]
can you specify some more things for me?
- what server type you're using (spigot/paper/purpur/etc.)
- what version of the plugin and what version of minecraft you're using
- a list of other plugins you're using that might interfere with anvil mechanics
- the items you're trying to combine that the anvil won't work with


for me it works fine, but i know there are minor differences across server jars that might break the mechanics and there might be plugins that override the anvil changes EnchantsSquared is attempting to make
