### ISSUE TITLE
Players are able to gain infinite flight

### ISSUE THREAD

**Issue by FrostyCirno** [Athlaeos/EnchantsSquared#4]
Players with flight on their boots can take them off mid-flight. This will cause the flight duration bar to disappear and stop. This allows for infinite flight.

**Comment by Athlaeos** [comment]
is this for all players? there are additional conditions with the plugin where if the player is either opped or has the essentials.fly permission they will keep their flight regardless if they have boots or not. if this occurs for non-opped players i will investigate

**Comment by FrostyCirno** [comment]
It only affect players with op, sorry for the hassle.
