### ISSUE TITLE
GitHub not updated to 1.6.2

### ISSUE THREAD

**Issue by ChillyTheEevee** [Athlaeos/EnchantsSquared#6]
Hey!

I've been sifting around in the code for about an hour customizing the plugin even more for a server my friends and I will be hosting and from what I can tell it looks like the code is out of date with the current Jar file on spigotmc.org! I can't run it on 1.19.2 anymore. Can you update the repo? Sorry to get in your hair! Big fan of this plugin.

Thanks!

**Comment by Athlaeos** [comment]
Oh you poor child, I'm so sorry. I'm about to release a completely rewritten version of the plugin and I'm not sure I'll be maintaining the old one further :P

If you tell me what error occurs on 1.19.2, I'll fix it though

**Comment by ChillyTheEevee** [comment]
Ohhh boyyyy okay well that's completely fine Athlaeos I appreciate it! The server's not gonna be up for another like year so I think we'll just transition to the rewritten one then! That's amazing.

Appreciate the help! Looking forward to seeing the new plugin, sounds awesome. I'll be sure to watch it
